#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image: Visual Studio 2019
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: //RzPD6sJwALrAUPet5ffD2C82ETjhYb1XR30sWRHtqNK5E9Q9xN96GNP9OfWCwX
  CODECOV_TOKEN:
    secure: KE2A2I2gpzWzC8fqWQDW/4lOcCJH54j2A6MATbxRaoQUwTwp7bF0/2EupHxq01eV
  NUGET_TOKEN:
    secure: i1Aml1iC2Cq8qJTm/uAMK3aa/ZNlaVV+LISMuH8ebYlmZwFo3A4rRo9sok71XgPc
  APPVEYOR_TOKEN:
    secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off
