#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image: Visual Studio 2019
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: dX0nMylhx+PlCOs07DPD6nxfCfFGIpb7psC5bXSAxkRRuBOggUQf3LJjxaZ3jCgw
  CODECOV_TOKEN:
    secure: KE2A2I2gpzWzC8fqWQDW/4lOcCJH54j2A6MATbxRaoQUwTwp7bF0/2EupHxq01eV
  NUGET_TOKEN:
    secure: ZDvc2hL3H+4ubTi1cibTM+XeOJVXEzhuMCnDxOL8Hs2e9unfRUHrCwYC52IVjXjh
  APPVEYOR_TOKEN:
    secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off
