#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: dX0nMylhx+PlCOs07DPD6nxfCfFGIpb7psC5bXSAxkRRuBOggUQf3LJjxaZ3jCgw
  CODECOV_TOKEN:
    secure: KE2A2I2gpzWzC8fqWQDW/4lOcCJH54j2A6MATbxRaoQUwTwp7bF0/2EupHxq01eV
  NUGET_TOKEN:
    secure: P2AbVXF6ZhkWoNAFjmIhzMH3FEgJkFtXPozru7MTOWRn6HCRiq3Dz+TP36knnevg
  APPVEYOR_TOKEN:
    secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off
