#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: tvoyJ/iv8Y+9VaKvOFvxegvQFBNqPkhiwghS8lQDsrt7B/1MWU4e8uOHQzfTU580
  CODECOV_TOKEN:
    secure: 2/6E5a1yzv5Wp1yRpHGDybeKyjdyJlO2xiRxuT4TBGBJcbSfjOrMRsFpMd/X334f
  NUGET_TOKEN:
    secure: P2AbVXF6ZhkWoNAFjmIhzMH3FEgJkFtXPozru7MTOWRn6HCRiq3Dz+TP36knnevg
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off
