#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: '.\artifacts\**\*.nupkg'
- path: '.\artifacts\**\yaapii.Xml.Xambly.xml'
deploy:
  - provider: NuGet
    name: AppVeyor Feed
    on:
      branch: master # Deploy only on master branch
      appveyor_repo_tag: true
    server: https://ci.appveyor.com/nuget/icarus
    api_key:
      secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
    skip_symbols: true
    artifact: /.*\.nupkg/
- provider: NuGet
    name: Nuget feed
    on:
      branch: master
      appveyor_repo_tag: true
    api_key:
      secure: AuUbKCY+YVcotkpwDEqZMGpK3G64913kOq3+Xt9DYBCZbdADh/xYvHHatjirUpy/
    skip_symbols: false
    artifact: /.*\.nupkg/
