//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Xembly.g by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


    
    import java.util.Collection;
    import java.util.LinkedList;

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class XemblyLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, DIGIT=14, COMMA=15, COLON=16, SEMICOLON=17, 
		TEXT=18, SPACE=19;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "DIGIT", "COMMA", "COLON", "SEMICOLON", 
		"TEXT", "SPACE"
	};


	    @Override
	    public void emitErrorMessage(String msg) {
	        throw new ParsingException(msg);
	    }


	public XemblyLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public XemblyLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'XPATH'", "'SET'", "'XSET'", "'ATTR'", "'ADD'", "'ADDIF'", "'REMOVE'", 
		"'STRICT'", "'UP'", "'PI'", "'PUSH'", "'POP'", "'CDATA'", null, "','", 
		"':'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "DIGIT", "COMMA", "COLON", "SEMICOLON", "TEXT", "SPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Xembly.g"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static XemblyLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	public override void Action(RuleContext _localctx, int ruleIndex, int actionIndex) {
		switch (ruleIndex) {
		case 17 : TEXT_action(_localctx, actionIndex); break;
		case 18 : SPACE_action(_localctx, actionIndex); break;
		}
	}
	private void TEXT_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 0: 
		        try {
		            this.setText(Arg.unescape(this.getText()));
		        } catch (final XmlContentException ex) {
		            throw new ParsingException(ex);
		        }
		     break;
		case 1: 
		        try {
		            this.setText(Arg.unescape(this.getText()));
		        } catch (final XmlContentException ex) {
		            throw new ParsingException(ex);
		        }
		     break;
		}
	}
	private void SPACE_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 2:  skip();  break;
		}
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x15', '\x8D', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', 
		'u', '\n', '\x13', '\f', '\x13', '\xE', '\x13', 'x', '\v', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '~', 
		'\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x81', '\v', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x5', '\x13', '\x85', '\n', '\x13', '\x3', '\x14', 
		'\x6', '\x14', '\x88', '\n', '\x14', '\r', '\x14', '\xE', '\x14', '\x89', 
		'\x3', '\x14', '\x3', '\x14', '\x2', '\x2', '\x15', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', 
		'\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', 
		'%', '\x14', '\'', '\x15', '\x3', '\x2', '\x5', '\x3', '\x2', '$', '$', 
		'\x3', '\x2', ')', ')', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', 
		'\"', '\x2', '\x90', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x3', ')', '\x3', '\x2', '\x2', '\x2', '\x5', '/', '\x3', 
		'\x2', '\x2', '\x2', '\a', '\x33', '\x3', '\x2', '\x2', '\x2', '\t', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\v', '=', '\x3', '\x2', '\x2', '\x2', '\r', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\xF', 'G', '\x3', '\x2', '\x2', '\x2', 
		'\x11', 'N', '\x3', '\x2', '\x2', '\x2', '\x13', 'U', '\x3', '\x2', '\x2', 
		'\x2', '\x15', 'X', '\x3', '\x2', '\x2', '\x2', '\x17', '[', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '`', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x64', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', 'j', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'l', '\x3', '\x2', '\x2', '\x2', '!', 'n', '\x3', '\x2', '\x2', '\x2', 
		'#', 'p', '\x3', '\x2', '\x2', '\x2', '%', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\x87', '\x3', '\x2', '\x2', '\x2', ')', '*', '\a', 'Z', 
		'\x2', '\x2', '*', '+', '\a', 'R', '\x2', '\x2', '+', ',', '\a', '\x43', 
		'\x2', '\x2', ',', '-', '\a', 'V', '\x2', '\x2', '-', '.', '\a', 'J', 
		'\x2', '\x2', '.', '\x4', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\a', 
		'U', '\x2', '\x2', '\x30', '\x31', '\a', 'G', '\x2', '\x2', '\x31', '\x32', 
		'\a', 'V', '\x2', '\x2', '\x32', '\x6', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\x34', '\a', 'Z', '\x2', '\x2', '\x34', '\x35', '\a', 'U', '\x2', '\x2', 
		'\x35', '\x36', '\a', 'G', '\x2', '\x2', '\x36', '\x37', '\a', 'V', '\x2', 
		'\x2', '\x37', '\b', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\a', 
		'\x43', '\x2', '\x2', '\x39', ':', '\a', 'V', '\x2', '\x2', ':', ';', 
		'\a', 'V', '\x2', '\x2', ';', '<', '\a', 'T', '\x2', '\x2', '<', '\n', 
		'\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '\x43', '\x2', '\x2', '>', 
		'?', '\a', '\x46', '\x2', '\x2', '?', '@', '\a', '\x46', '\x2', '\x2', 
		'@', '\f', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\x43', '\x2', 
		'\x2', '\x42', '\x43', '\a', '\x46', '\x2', '\x2', '\x43', '\x44', '\a', 
		'\x46', '\x2', '\x2', '\x44', '\x45', '\a', 'K', '\x2', '\x2', '\x45', 
		'\x46', '\a', 'H', '\x2', '\x2', '\x46', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'G', 'H', '\a', 'T', '\x2', '\x2', 'H', 'I', '\a', 'G', '\x2', '\x2', 
		'I', 'J', '\a', 'O', '\x2', '\x2', 'J', 'K', '\a', 'Q', '\x2', '\x2', 
		'K', 'L', '\a', 'X', '\x2', '\x2', 'L', 'M', '\a', 'G', '\x2', '\x2', 
		'M', '\x10', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\a', 'U', '\x2', '\x2', 
		'O', 'P', '\a', 'V', '\x2', '\x2', 'P', 'Q', '\a', 'T', '\x2', '\x2', 
		'Q', 'R', '\a', 'K', '\x2', '\x2', 'R', 'S', '\a', '\x45', '\x2', '\x2', 
		'S', 'T', '\a', 'V', '\x2', '\x2', 'T', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'U', 'V', '\a', 'W', '\x2', '\x2', 'V', 'W', '\a', 'R', '\x2', '\x2', 
		'W', '\x14', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\a', 'R', '\x2', '\x2', 
		'Y', 'Z', '\a', 'K', '\x2', '\x2', 'Z', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'[', '\\', '\a', 'R', '\x2', '\x2', '\\', ']', '\a', 'W', '\x2', '\x2', 
		']', '^', '\a', 'U', '\x2', '\x2', '^', '_', '\a', 'J', '\x2', '\x2', 
		'_', '\x18', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', 'R', '\x2', 
		'\x2', '\x61', '\x62', '\a', 'Q', '\x2', '\x2', '\x62', '\x63', '\a', 
		'R', '\x2', '\x2', '\x63', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\a', '\x45', '\x2', '\x2', '\x65', '\x66', '\a', '\x46', '\x2', 
		'\x2', '\x66', 'g', '\a', '\x43', '\x2', '\x2', 'g', 'h', '\a', 'V', '\x2', 
		'\x2', 'h', 'i', '\a', '\x43', '\x2', '\x2', 'i', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'k', '\x4', '\x32', ';', '\x2', 'k', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', 'l', 'm', '\a', '.', '\x2', '\x2', 'm', ' ', '\x3', 
		'\x2', '\x2', '\x2', 'n', 'o', '\a', '<', '\x2', '\x2', 'o', '\"', '\x3', 
		'\x2', '\x2', '\x2', 'p', 'q', '\a', '=', '\x2', '\x2', 'q', '$', '\x3', 
		'\x2', '\x2', '\x2', 'r', 'v', '\a', '$', '\x2', '\x2', 's', 'u', '\n', 
		'\x2', '\x2', '\x2', 't', 's', '\x3', '\x2', '\x2', '\x2', 'u', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'y', '\x3', '\x2', '\x2', '\x2', 'x', 'v', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'z', '\a', '$', '\x2', '\x2', 'z', '\x85', '\b', 
		'\x13', '\x2', '\x2', '{', '\x7F', '\a', ')', '\x2', '\x2', '|', '~', 
		'\n', '\x3', '\x2', '\x2', '}', '|', '\x3', '\x2', '\x2', '\x2', '~', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x7F', '}', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', '\x2', '\x80', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\a', ')', '\x2', '\x2', '\x83', '\x85', '\b', '\x13', '\x3', 
		'\x2', '\x84', 'r', '\x3', '\x2', '\x2', '\x2', '\x84', '{', '\x3', '\x2', 
		'\x2', '\x2', '\x85', '&', '\x3', '\x2', '\x2', '\x2', '\x86', '\x88', 
		'\t', '\x4', '\x2', '\x2', '\x87', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x88', '\x89', '\x3', '\x2', '\x2', '\x2', '\x89', '\x87', '\x3', '\x2', 
		'\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\b', '\x14', '\x4', '\x2', 
		'\x8C', '(', '\x3', '\x2', '\x2', '\x2', '\a', '\x2', 'v', '\x7F', '\x84', 
		'\x89', '\x5', '\x3', '\x13', '\x2', '\x3', '\x13', '\x3', '\x3', '\x14', 
		'\x4',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
